iBanking/Models/AspNetUser.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBanking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetUser()
        {
            this.AspNetUsers1 = new HashSet<AspNetUser>();
            this.Transitions = new HashSet<Transition>();
        }
    
        public int Id { get; set; }
        public string Email { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public Nullable<int> ManagerID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public int RoleID { get; set; }
        public int BranchID { get; set; }
    
        public virtual AspNetRole AspNetRole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUser> AspNetUsers1 { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transition> Transitions { get; set; }
        public virtual Branch Branch { get; set; }
    }
}

iBanking/Controllers/AspNetUsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using iBanking.Models;

namespace iBanking.Controllers
{
    public class AspNetUsersController : Controller
    {
        private BankingSystemEntities db = new BankingSystemEntities();

        // GET: AspNetUsers
        public ActionResult Index()
        {
            var Currentuser = Session["CurrentUser"];
            if (Currentuser == null)
            {
                return RedirectToAction("Login", "Account");
            }
            ViewBag.Currentuser = Currentuser;
            var URL = Request.Url.AbsoluteUri;
            ViewBag.URL = URL;
            int userid = Convert.ToInt32(Currentuser);
            AspNetUser user = db.AspNetUsers.FirstOrDefault(a => a.Id == userid);
            ViewBag.UserRole = user.RoleID;
            List<AspNetUser> UserList = new List<AspNetUser>();
            if(user.RoleID == 1)
            {
                UserList.AddRange(db.AspNetUsers.ToList());
            }
            else
            {
                UserList.AddRange(db.AspNetUsers.Where(a => a.BranchID == user.BranchID).ToList());
            }
            var aspNetUsers = db.AspNetUsers.Include(a => a.AspNetUser1);
            return View(aspNetUsers.ToList());
        }

        // GET: AspNetUsers/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetUser aspNetUser = db.AspNetUsers.Find(id);
            if (aspNetUser == null)
            {
                return HttpNotFound();
            }
            return View(aspNetUser);
        }

        // GET: AspNetUsers/Create
        public ActionResult Create()
        {
            var Currentuser = Session["CurrentUser"];
            if (Currentuser == null)
            {
                return RedirectToAction("Login", "Account");
            }
            ViewBag.Currentuser = Currentuser;
            var URL = Request.Url.AbsoluteUri;
            ViewBag.URL = URL;
            int userid = Convert.ToInt32(Currentuser);
            AspNetUser user = db.AspNetUsers.FirstOrDefault(a => a.Id == userid);
            ViewBag.UserRole = user.RoleID;
            ViewBag.ManagerID = new SelectList(db.AspNetUsers.Where(a => a.RoleID < 3 && a.BranchID == user.BranchID), "Id", "Name");
            ViewBag.BranchID = new SelectList(db.Branches.Where(a => a.ID > 1), "ID", "Name");
            ViewBag.RoleID = new SelectList(db.AspNetRoles.Where(a => a.Id > user.RoleID), "ID", "Name");
            return View();
        }

        // POST: AspNetUsers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(AspNetUser aspNetUser)
        {
            var Currentuser = Session["CurrentUser"];
            if (Currentuser == null)
            {
                return RedirectToAction("Login", "Account");
            }
            ViewBag.Currentuser = Currentuser;
            var URL = Request.Url.AbsoluteUri;
            ViewBag.URL = URL;
            AspNetUser existinguser = db.AspNetUsers.FirstOrDefault(a => a.Name == aspNetUser.Name);
            if (existinguser != null)
            {
                ModelState.AddModelError("Name", "Already have in database!!!");
            }
            if (ModelState.IsValid)
            {
                aspNetUser.CreatedDate = DateTime.Now;
                aspNetUser.BranchID = aspNetUser.BranchID;
                aspNetUser.UserName = aspNetUser.Name;
                aspNetUser.Password = "12345";
                db.AspNetUsers.Add(aspNetUser);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            int userid = Convert.ToInt32(Currentuser);
            AspNetUser user = db.AspNetUsers.FirstOrDefault(a => a.Id == userid);
            ViewBag.UserRole = user.RoleID;
            ViewBag.ManagerID = new SelectList(db.AspNetUsers.Where(a => a.RoleID < 3 && a.BranchID == user.BranchID), "Id", "Name", aspNetUser.ManagerID);
            ViewBag.BranchID = new SelectList(db.Branches.Where(a => a.ID > 1), "ID", "Name", aspNetUser.BranchID);
            ViewBag.RoleID = new SelectList(db.AspNetRoles.Where(a => a.Id > user.RoleID), "ID", "Name", aspNetUser.RoleID);
            return View(aspNetUser);
        }

        // GET: AspNetUsers/Edit/5
        public ActionResult Edit(string id)
        {
            var Currentuser = Session["CurrentUser"];
            if (Currentuser == null)
            {
                return RedirectToAction("Login", "Account");
            }
            ViewBag.Currentuser = Currentuser;
            var URL = Request.Url.AbsoluteUri;
            ViewBag.URL = URL;
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            int UserID = Convert.ToInt32(id);
            AspNetUser aspNetUser = db.AspNetUsers.Find(UserID);
            if (aspNetUser == null)
            {
                return HttpNotFound();
            }
            int userid = Convert.ToInt32(Currentuser);
            AspNetUser user = db.AspNetUsers.FirstOrDefault(a => a.Id == userid);
            ViewBag.UserRole = user.RoleID;
            ViewBag.ManagerID = new SelectList(db.AspNetUsers.Where(a => a.RoleID < 3 && a.BranchID == user.BranchID), "Id", "Name", aspNetUser.ManagerID);
            ViewBag.BranchID = new SelectList(db.Branches.Where(a => a.ID > 1), "ID", "Name", aspNetUser.BranchID);
            ViewBag.RoleID = new SelectList(db.AspNetRoles.Where(a => a.Id > user.RoleID), "ID", "Name", aspNetUser.RoleID);
            return View(aspNetUser);
        }

        // POST: AspNetUsers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(AspNetUser aspNetUser)
        {
            var Currentuser = Session["CurrentUser"];
            if (Currentuser == null)
            {
                return RedirectToAction("Login", "Account");
            }
            ViewBag.Currentuser = Currentuser;
            var URL = Request.Url.AbsoluteUri;
            ViewBag.URL = URL;
            if (ModelState.IsValid)
            {
                db.Entry(aspNetUser).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            int userid = Convert.ToInt32(Currentuser);
            AspNetUser user = db.AspNetUsers.FirstOrDefault(a => a.Id == userid);
            ViewBag.UserRole = user.RoleID;
            ViewBag.ManagerID = new SelectList(db.AspNetUsers.Where(a => a.RoleID < 3 && a.BranchID == user.BranchID), "Id", "Name", aspNetUser.ManagerID);
            ViewBag.BranchID = new SelectList(db.Branches.Where(a => a.ID > 1), "ID", "Name", aspNetUser.BranchID);
            ViewBag.RoleID = new SelectList(db.AspNetRoles.Where(a => a.Id > user.RoleID), "ID", "Name", aspNetUser.RoleID);
            return View(aspNetUser);
        }

        // GET: AspNetUsers/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AspNetUser aspNetUser = db.AspNetUsers.Find(id);
            if (aspNetUser == null)
            {
                return HttpNotFound();
            }
            return View(aspNetUser);
        }

        // POST: AspNetUsers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            AspNetUser aspNetUser = db.AspNetUsers.Find(id);
            db.AspNetUsers.Remove(aspNetUser);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

iBanking/Views/AspNetUsers/Create.cshtml
@model iBanking.Models.AspNetUser

@{
    ViewBag.Title = "Create";
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal" style="background-color:#EDEDED; padding: 10px 0px 10px 0px;">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <p class="col-md-3 control-label " style="text-align:right; padding-right:5px;">User name :</p>
            <div class="col-md-2">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>

            <p class="col-md-1 control-label" style="text-align:right; padding-right:5px;visibility:visible">Email :</p>
            <div class="col-md-6">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <p class="col-md-3 control-label " style="text-align:right; padding-right:5px;">Role :</p>
            <div class="col-md-2">
                @Html.DropDownList("RoleID", null, "Please select...", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RoleID, "", new { @class = "text-danger" })
            </div>

            <p class="col-md-1 control-label" style="text-align:right; padding-right:5px;">Manager Name :</p>
            <div class="col-md-6">
                @Html.DropDownList("ManagerID", null, "Please select...", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ManagerID, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            <p class="col-md-3 control-label " style="text-align:right; padding-right:5px;">Branch :</p>
            <div class="col-md-2">
                @Html.DropDownList("BranchID", null, "Please select...", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.BranchID, "", new { @class = "text-danger" })
            </div>

        </div>
        <div class="form-group">
            <div class="col-md-offset-3 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" /> |
                <a href="/AspNetUsers/Index" class="btn btn-default">Back to list</a>
            </div>
        </div>
    </div>
}

iBanking/Views/AspNetUsers/Delete.cshtml
@model iBanking.Models.AspNetUser

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>AspNetUser</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmailConfirmed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmailConfirmed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PasswordHash)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PasswordHash)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SecurityStamp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SecurityStamp)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumberConfirmed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumberConfirmed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TwoFactorEnabled)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TwoFactorEnabled)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LockoutEndDateUtc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LockoutEndDateUtc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LockoutEnabled)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LockoutEnabled)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AccessFailedCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AccessFailedCount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Question)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Question)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Answer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Answer)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PasswordChangeRequired)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PasswordChangeRequired)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PasswordResetDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PasswordResetDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RoutineJob)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RoutineJob)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LeaveDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LeaveDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AspNetUser1.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AspNetUser1.Email)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

iBanking/Views/AspNetUsers/Details.cshtml
@model iBanking.Models.AspNetUser

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>AspNetUser</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmailConfirmed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmailConfirmed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PasswordHash)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PasswordHash)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SecurityStamp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SecurityStamp)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumberConfirmed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumberConfirmed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TwoFactorEnabled)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TwoFactorEnabled)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LockoutEndDateUtc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LockoutEndDateUtc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LockoutEnabled)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LockoutEnabled)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AccessFailedCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AccessFailedCount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Question)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Question)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Answer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Answer)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PasswordChangeRequired)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PasswordChangeRequired)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PasswordResetDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PasswordResetDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RoutineJob)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RoutineJob)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LeaveDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LeaveDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AspNetUser1.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AspNetUser1.Email)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

iBanking/Views/AspNetUsers/Edit.cshtml
@model iBanking.Models.AspNetUser

@{
    ViewBag.Title = "Edit";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal" style="background-color:#EDEDED; padding: 10px 0px 10px 0px;">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.UserName)
        @Html.HiddenFor(model => model.CreatedDate)
        @Html.HiddenFor(model => model.Password)

        <div class="form-group">
            <p class="col-md-3 control-label " style="text-align:right; padding-right:5px;">Name :</p>
            <div class="col-md-2">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>

            <p class="col-md-1 control-label" style="text-align:right; padding-right:5px;visibility:visible">Email :</p>
            <div class="col-md-6">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            <p class="col-md-3 control-label " style="text-align:right; padding-right:5px;">Role :</p>
            <div class="col-md-2">
                @Html.DropDownList("RoleID", null, "Please select...", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RoleID, "", new { @class = "text-danger" })
            </div>

            <p class="col-md-1 control-label" style="text-align:right; padding-right:5px;">Manager Name :</p>
            <div class="col-md-6">
                @Html.DropDownList("ManagerID", null, "Please select...", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ManagerID, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            <p class="col-md-3 control-label " style="text-align:right; padding-right:5px;">Branch :</p>
            <div class="col-md-2">
                @Html.DropDownList("BranchID", null, "Please select...", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.BranchID, "", new { @class = "text-danger" })
            </div>

        </div>

        <div class="form-group">
            <div class="col-md-offset-3 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" /> |
                <a href="/AspNetUsers/Index" class="btn btn-default">Back to list</a>
            </div>
        </div>
    </div>
}

iBanking/Views/AspNetUsers/Index.cshtml
@model IEnumerable<iBanking.Models.AspNetUser>

@{
    ViewBag.Title = "Index";
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserName)
        </th>
        <th>
            Manager
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </th>
        @if (ViewBag.UserRole != 3)
        {
            <th>
                <a class="btn btn-success" style="height: 30px; font-size: smaller;" href="@Url.Action("Create", "AspNetUsers")">Create New</a>
            </th>
        }
        else
        {
            <th></th>
        }
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AspNetUser1.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreatedDate)
        </td>
        @if (ViewBag.UserRole != 3)
        {
            <td>
                <a class="btn btn-default" style="height: 20px; padding-top: 2px; font-size: x-small;" href="@Url.Action("Edit", "AspNetUsers", new { id = item.Id })">Edit</a>
            </td>
        }
        else
        {
            <td></td>
        }
    </tr>
}

</table>